### ISSUE TITLE
好多书看不了

### ISSUE THREAD

**Issue by 2366621450** [zimplexing/vue-nReader#15]
10本有8本看不了，换源也只是碰运气，.难道是我这边的问题吗？
请答复谢谢

**Comment by zimplexing** [comment]
换源是调的接口，如果出现问题，可以看下换源接口返回的数据是否正确。

**Comment by 2366621450** [comment]
换源的返回数据是没有错的。

就是 获取节章内容 这一块出现 
{"ok":false,"message":"{\"ok\":false,\"code\":\"BAD_LINK\"}"}

你看 http://chapterup.zhuishushenqi.com/chapter/http://vip.zhuishushenqi.com/chapter/http://book.my716.com/getBooks.aspx?method=content&bookId=1367041&chapterFile=U_1367041_201707270927218840_8820_1.txt

**Comment by 2366621450** [comment]
换源的返回数据是没有错的。

就是 获取节章内容 这一块出现 
{"ok":false,"message":"{\"ok\":false,\"code\":\"BAD_LINK\"}"}

你看 http://chapterup.zhuishushenqi.com/chapter/http://vip.zhuishushenqi.com/chapter/http://book.my716.com/getBooks.aspx?method=content&bookId=1367041&chapterFile=U_1367041_201707270927218840_8820_1.txt

**Comment by zimplexing** [comment]
这个应该是接口的问题，接口这块我也好久没有看过了，不知道是不是官方把接口封了或者改了

**Comment by 2366621450** [comment]
好吧...能修复吗？

**Comment by zimplexing** [comment]
这个需要重新抓下包。你可以看看novel.juhe.im 这个提供的接口，应该都差不多。

**Comment by 2366621450** [comment]
他那个早蹦了，所以我才来你这个....
