### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by xiaoshanyuhe** [zimplexing/vue-nReader#2]
src\components\Bookcat.vue中第45行'console'写错;
src\main.js中的baseURL配的是localhost:3000,本地运行时就看见加载动画,乏味!,将其改为'http://api.zhuishushenqi.com'时,会出现跨域问题;望改进~~

**Comment by zimplexing** [comment]
本地启动项目 需要在本地启动一个访问api.zhuishushenqi.com的代理， 或者是使用http://35.189.165.140:3000 这个是我部署在虚拟主机上代理
