### ISSUE TITLE
打包后提示http不安全

### ISSUE THREAD

**Issue by yydelight** [zimplexing/vue-nReader#8]
接口在本地运行没问题，但是打包上传到github上之后就会失效，就会报错...was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://35.189.165.140:3000/book/search-hotwords'. This request has been blocked; the content must be served over HTTPS.
这应该怎么解决呢？

**Comment by zimplexing** [comment]
这个是因为代理是http的,github.io是https的提示不安全是浏览器的行为，统一协议即可
